services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: "mongodb+srv://YenNhi:nhi12345@cluster0.21egefp.mongodb.net/?appName=Cluster0"

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend